queries = {"asin_category_query": '''CREATE TABLE ASIN_Category
          (name_cat_lvl1 varchar,
           name_cat_lvl2 varchar,
           name_cat_lvl3 varchar,
           name_cat_lvl4 varchar,
           name_cat_lvl5 varchar,
           asin varchar unique); ''',
     
    'asin_product_page_query': '''CREATE TABLE ASIN_Product_Page
          (url varchar,
           asin varchar UNIQUE,
           Product_Length NUMERIC(5,2),
           Product_Width NUMERIC,
           Product_Height NUMERIC,
           Product_Dimension_Unit varchar,
           Product_Weight NUMERIC(5,2),
           Product_Weight_Unit TEXT,
           Package_Length NUMERIC(5,2),
           Package_Width NUMERIC(5,2),
           Package_Height NUMERIC(5,2),
           Category varchar,
           name varchar,
           brand varchar,
           seller varchar,
           seller_url varchar,
           review_count NUMERIC(5,2),
           rating  NUMERIC(5,2),
           currency varchar,
           sale_price NUMERIC(5,2),
           regular_price NUMERIC(5,2),
           shipping_charge NUMERIC(5,2),
           small_description varchar,
           full_description varchar,
           availability_status varchar,
           available_quantity NUMERIC(5,2),
           model varchar,
           attributes varchar,
           product_category varchar,
           product_information varchar,
           highlighted_specifications varchar,
           image_urls varchar,
           variation_asin varchar,
           product_variations varchar,
           frequently_bought_together varchar,
           product_reviews varchar,
           sponsored_products varchar,
           rating_histogram varchar); ''',
     
    'master_keywords_market_query': '''CREATE TABLE Master_KeyWords_Market_Insights
          (asin varchar,
           Keyword varchar UNIQUE,
           market_lifetime INT,
           avg_sales_listed INT,
           orders_per_month INT,
           avg_sales_per_month INT,
           active_competing_products INT,
           avg_price DOUBLE PRECISION,
           estimated_profit_margin varchar,
           estimated_cogs varchar,
           market_maturity varchar,
           market_capacity varchar,
           market_competition varchar,
           market_fund varchar,
           market_concentration varchar,
           market_activeness INT,
           sales_attribution_reviews INT,
           sales_attribution_price NUMERIC(5,2),
           sales_attribution_product_video NUMERIC(5,2),
           sales_attribution_Aplustcontent NUMERIC(5,2),
           sales_attribution_coupon NUMERIC(5,2),
           sales_attribution_time_listed NUMERIC(5,2),
           sales_attribution_customer_rating NUMERIC(5,2),
           sales_attribution_variation NUMERIC(5,2),
           sales_attribution_seller_type NUMERIC(5,2),
           sales_attribution_others NUMERIC(5,2),
           top10_order_per_day INT,
           top20_order_per_day INT,
           top50_order_per_day INT,
           top100_order_per_day INT,
           top10_min_reviews INT,
           top20_min_reviews INT,
           top50_min_reviews INT,
           top100_min_reviews INT); '''}

data = {
    "host"      : "test-wrapfy-1.c9dyjmixlq3h.us-east-2.rds.amazonaws.com",
    "database"  : "wrapfy_test",
    "user"      : "test_postgre_1",
    "password"  : "wrapfytesting",
    "port"      : "5432"
}